[package]
name = "md_note"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.33"
regex = "1.10.2"
reqwest = "0.11.24"
tokio = { version = "1.36.0", features = ["full"] }